name: Scan Specified Projects
on:
  workflow_dispatch:
  # uncomment below and adjust to frequency to automatically run
  # schedule:
  #   - cron: 1 */2 * * *
    
jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            repos.csv
          sparse-checkout-cone-mode: false
      
      - name: Read repos and namespaces from CSV
        id: set-matrix
        run: |
          OUTPUT="$(awk -F',' '{print "{\"repo\":\"" $1 "\", \"namespace\":\"" $2 "\"}"}' repos.csv | jq -s '.' | tr '\n' ' ')"
          echo $OUTPUT
          echo "matrix=$OUTPUT" >> $GITHUB_ENV

  scan-matrix:
    needs: generate_matrix
    strategy:
      # fail-fast should be set false so that one scan failure doesn't stop the whole matrix
      fail-fast: false
      max-parallel: 5
      matrix: 
        projects: ${{ fromJSON(needs.generate_matrix.outputs.matrix) }}
    uses: nmichalov/endor-labs-supervisory-scan/.github/workflows/scan-with-endorlabs.yml@main
    permissions:
      id-token: write      # allows authentication to Endor Labs using Actions OIDC JWT Token
      pull-requests: write # allows scanner to leave a pull request comment, if enabled
      issues: write        # allows scanner to leave a PR comment, if enabled
      contents: read       # allows this job to clone org repos
    with:
      git-url: ${{ matrix.projects.repo }}
      namespace: ${{ matrix.projects.namespace }}
